name: 'Intall'
description: 'Sets up the repository'
inputs:
  node-version: # node version on which to build
    description: "Node version for the build"
    required: true
    default: 'latest'
runs:
  using: 'composite'
  steps:
    - name: Set up pnpm
      # pnpm version controlled in top level package.json
      uses: pnpm/action-setup@v4
    - name: Install NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
    # pnpm doesn't do this? ¯\_(ツ)_/¯
    # needed for linting
    - name: Link globals package
      shell: bash
      run: ln -s node_modules/.pnpm/globals@15.6.0/node_modules/globals/ node_modules/globals