name: Tests
on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/install
      - name: Run lint
        run: pnpm lint

  unit-tests:
    strategy:
      matrix:
        install-node-versions: [18.x, stable]
    runs-on: ubuntu-latest
    env:
      # sync with /package/test/docker-compose.yaml
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/pgv-test?schema=public
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/install
        with:
          node-version: ${{ matrix.install-node-versions }}
      - uses: ./.github/workflows/docker-compose
      - name: Run tests
        run: pnpm test:unit